name: Release Candidate Workflow

#on:
#  pull_request:

on:
  push:
    branches: ['DAT-4405-remove-travis-cicd-impl']

jobs:
  go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.4
        with:
          go-version: 1.18
      - name: Go Build With Tags
        run: go build -tags staging
      - name: Go Test
        run: go test ./...
