name: Release Candidate Workflow

#on:
#  workflow_dispatch:
on:
  push:
    branches: ['DAT-4405-remove-travis-cicd-impl']
env:
  GITHUB_ACTION_RUN_ID: ${{ github.run_id }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  go_build_and_test:
    uses: ./.github/workflows/reusable_go_build.yml
    with:
      goBuildTag: staging

  release_candidate:
    name: Release candidate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run deploy release candidate file
        run: |
          chmod +x ./scripts/deploy_release_candidate.sh
          ./scripts/deploy_release_candidate.sh
        shell: bash